# I2P Party Line - Distrobox manifest
# Usage: distrobox assemble create --file distrobox.ini
# Docs:  https://distrobox.it/usage/distrobox-assemble/

[partyline-i2p]
image=docker.io/marcusholtz/i2p-party-line-box:latest
pull=false
replace=false
init=false
root=false
exported_bins=/usr/local/bin/i2p-party-line.sh
exported_bins_path=~/.local/bin
